### ISSUE TITLE
Setup Instructions For Linux Users

### ISSUE THREAD

**Issue by trymeouteh** [travispessetto/OrigamiSMTP#10]
I have been trying for over a month to get this application to work on my Linux Mint 19.1 which has XAMPP installed on it. I tried configuring the php.ini file [mail function] that XAMPP offers to make these two applications work together and I have no luck.

Please make easy step by step instructions.

**Comment by travispessetto** [comment]
I need a bit more information.  Please answer the following questions:

- Are you using the installer or another way?
- Are you able to get the GUI or does it not show?

If you are having trouble with the GUI it is probably because it appears to only work with Oracle JRE and will require a few more steps.  I will try with PHP to see if I can work out any bugs I find.

**Comment by travispessetto** [comment]
php.ini SMTP settings only work on Windows.  You will need to follow the steps at https://github.com/travispessetto/OrigamiSMTP/wiki/PHP to use a custom SMTP server.  Note, since you are using XAMPP you will have to find where your php.ini file is.
