### ISSUE TITLE
Opening the GUI and app

### ISSUE THREAD

**Issue by jlovemec** [travispessetto/OrigamiSMTP#5]
I'm running a local drupal site (macOX) and OrigamiSMTP seems like a good option for me.
However, not being a java developer, I don't inherently understand how to launch the app.
The wiki assumes the GUI is open but does not cover launching it.
Please help?

Jeffrey Love
jlove@mec.ca

**Comment by travispessetto** [comment]
Hi, unfortunately OrigamiSMTP is not the easiest to use on a Mac as I have not yet found out how to make an installer with Travis-CI.  This may be fixed with Homebrew.  Your best option is to download the Jar and make sure you have Java installed.  Double clicking it should open the GUI.  For future issues or additional help please use https://pessetto.com/submit-ticket/.
